name: Bundle Package and Publish Release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./scripts

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Setup UV package manager
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13
          version: "latest"

      - name: Install dependencies
        run: uv pip install proof_frog pyinstaller

      - name: Bundle Windows package
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: & .\create_package.ps1

      - name: Bundle Linux or MacOS package
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          chmod +x ./create_package.sh
          ./create_package.sh

      - name: Upload built packages
        uses: actions/upload-artifact@v4
        with:
          name: pkg-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/proof_frog
